# Generated by Django 5.1.7 on 2025-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
