# Generated by Django 5.1.7 on 2025-03-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_cancellation_reason_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has confirmed receipt of the order'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the customer confirmed receipt of the order', null=True),
        ),
    ]
